# Generated by Django 3.2.16 on 2022-10-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221013_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
